--CREATE DATABASE SIESMA;

CREATE TABLE NIVEL_ACESSO (
	ID_NIVEL_ACESSO BIGINT PRIMARY KEY NOT NULL,
	NOME_ACESSO VARCHAR(30) NOT NULL
);

INSERT INTO NIVEL_ACESSO (ID_NIVEL_ACESSO, NOME_ACESSO) VALUES (1,'Administrativo');
COMMIT;
INSERT INTO NIVEL_ACESSO (ID_NIVEL_ACESSO, NOME_ACESSO) VALUES (2,'Docente');
COMMIT;
INSERT INTO NIVEL_ACESSO (ID_NIVEL_ACESSO, NOME_ACESSO) VALUES (3,'Aluno');
COMMIT;
INSERT INTO NIVEL_ACESSO (ID_NIVEL_ACESSO, NOME_ACESSO) VALUES (4,'Outros');
COMMIT;

CREATE TABLE USUARIO (
	ID_USUARIO BIGINT PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	RG VARCHAR(20) NOT NULL,
	ORGAO_EXPEDITOR VARCHAR(6) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TEL_CELULAR VARCHAR(20) NOT NULL,
	SENHA_USUARIO VARCHAR(20) NOT NULL,
	ID_NIVEL_ACESSO BIGINT NOT NULL,
	DT_CADASTRO TIMESTAMP NOT NULL,
	DT_FIM_VINCULO TIMESTAMP,
	FOREIGN KEY (ID_NIVEL_ACESSO) REFERENCES NIVEL_ACESSO (ID_NIVEL_ACESSO)
);

CREATE SEQUENCE USUARIO_ID_SEQ;
ALTER TABLE USUARIO ALTER COLUMN ID_USUARIO SET DEFAULT NEXTVAL('USUARIO_ID_SEQ');

CREATE TABLE FUNCAO (
	ID_FUNCAO BIGINT PRIMARY KEY NOT NULL,
	NOME_FUNCAO VARCHAR(30) NOT NULL
);

INSERT INTO FUNCAO (ID_FUNCAO, NOME_FUNCAO) VALUES (1,'Administrativo');
COMMIT;
INSERT INTO FUNCAO (ID_FUNCAO, NOME_FUNCAO) VALUES (2,'Docente');
COMMIT;

CREATE TABLE EMPREGADO (
	ID_USUARIO BIGINT NOT NULL,
	VALOR_HORA NUMERIC(12,2),
	ID_FUNCAO BIGINT NOT NULL
);

ALTER TABLE EMPREGADO ADD CONSTRAINT PK_EMPREGADO PRIMARY KEY(ID_USUARIO);
ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_PESSOA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_FUNCAO FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO (ID_FUNCAO);

CREATE TABLE UF (
	ID_UF BIGINT PRIMARY KEY NOT NULL,
	NOME_UF VARCHAR(30) NOT NULL,
	SG_UF VARCHAR(2) NOT NULL
);

INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (1,'Acre', 'AC');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (2,'Alagoas', 'AL');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (3,'Amapá', 'AP');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (4,'Amazonas', 'AM');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (5,'Bahia', 'BA');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (6,'Ceará', 'CE');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (7,'Distrito Federal', 'DF');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (8,'Espírito Santo', 'ES');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (9,'Goiás', 'GO');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (10,'Maranhão', 'MA');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (11,'Mato Grosso', 'MT');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (12,'Mato Grosso do Sul', 'MS');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (13,'Minas Gerais', 'MG');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (14,'Pará', 'PA');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (15,'Paraíba', 'PB');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (16,'Paraná', 'PR');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (17,'Pernambuco', 'PE');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (18,'Piauí', 'PI');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (19,'Rio de Janeiro', 'RJ');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (20,'Rio Grande do Norte', 'RN');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (21,'Rio Grande do Sul', 'RS');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (22,'Rondônia', 'RO');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (23,'Roraima', 'RR');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (24,'Santa Catarina', 'SC');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (25,'São Paulo', 'SP');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (26,'Sergipe', 'SE');
COMMIT;
INSERT INTO UF (ID_UF, NOME_UF, SG_UF) VALUES (27,'Tocantins', 'TO');
COMMIT;

CREATE TABLE GENERO (
	ID_GENERO BIGINT PRIMARY KEY NOT NULL,
	NOME_GENERO VARCHAR(30) NOT NULL
);

INSERT INTO GENERO (ID_GENERO, NOME_GENERO) VALUES (1,'Masculino');
COMMIT;
INSERT INTO GENERO (ID_GENERO, NOME_GENERO) VALUES (2,'Feminino');
COMMIT;
INSERT INTO GENERO (ID_GENERO, NOME_GENERO) VALUES (3,'Outros');
COMMIT;

CREATE TABLE ALUNO (
	ID_USUARIO BIGINT NOT NULL,
	DT_NASCIMENTO TIMESTAMP NOT NULL,
	ID_GENERO BIGINT NOT NULL,
	NATURALIDADE VARCHAR(50) NOT NULL,
	PROFISSAO VARCHAR(50),
	ENDERECO VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ID_UF BIGINT NOT NULL,
	CEP VARCHAR(20) NOT NULL,
	TEL_RESID VARCHAR(20),
	TEL_COMERCIAL VARCHAR(20),
	DT_VENCIMENTO TIMESTAMP NOT NULL,
	IES_GRADUACAO VARCHAR(50) NOT NULL,
	SITUACAO_COMERCIAL VARCHAR(50) NOT NULL
);

ALTER TABLE ALUNO ADD CONSTRAINT PK_ALUNO PRIMARY KEY(ID_USUARIO);
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_PESSOA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_UF FOREIGN KEY (ID_UF) REFERENCES UF (ID_UF);
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO (ID_GENERO);

CREATE TABLE CURSO (
	ID_CURSO BIGINT PRIMARY KEY NOT NULL,
	NOME_CURSO VARCHAR(30) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	VALOR_CURSO NUMERIC(12,2) NOT NULL
);

CREATE SEQUENCE CURSO_ID_SEQ;
ALTER TABLE CURSO ALTER COLUMN ID_CURSO SET DEFAULT NEXTVAL('CURSO_ID_SEQ');

CREATE TABLE MODULO (
	ID_MODULO BIGINT PRIMARY KEY NOT NULL,
	ID_CURSO BIGINT NOT NULL,
	NOME_MODULO VARCHAR(30) NOT NULL,
	DT_INICIO TIMESTAMP NOT NULL,
	DT_FIM TIMESTAMP NOT NULL
);

CREATE SEQUENCE MODULO_ID_SEQ;
ALTER TABLE MODULO ALTER COLUMN ID_MODULO SET DEFAULT NEXTVAL('MODULO_ID_SEQ');
ALTER TABLE MODULO ADD CONSTRAINT FK_MODULO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

CREATE TABLE DISCIPLINA (
	ID_DISCIPLINA BIGINT PRIMARY KEY NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	NOME_DISCIPLINA VARCHAR(30) NOT NULL,
	DT_INICIO TIMESTAMP NOT NULL,
	DT_FIM TIMESTAMP NOT NULL
);

CREATE SEQUENCE DISCIPLINA_ID_SEQ;
ALTER TABLE DISCIPLINA ALTER COLUMN ID_DISCIPLINA SET DEFAULT NEXTVAL('DISCIPLINA_ID_SEQ');
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_EMPREGADO FOREIGN KEY (ID_USUARIO) REFERENCES EMPREGADO (ID_USUARIO);
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_MODULO FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO);


CREATE TABLE MATRICULA (
	ID_MATRICULA BIGINT PRIMARY KEY NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	ID_CURSO BIGINT NOT NULL,
	DT_MATRICULA TIMESTAMP NOT NULL,
	DT_FIM_PREVISTO TIMESTAMP,
	DT_FIM_EFETIVA TIMESTAMP,
	DT_CANCELAMENTO TIMESTAMP
);

CREATE SEQUENCE MATRICULA_ID_SEQ;
ALTER TABLE MATRICULA ALTER COLUMN ID_MATRICULA SET DEFAULT NEXTVAL('MATRICULA_ID_SEQ');
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ID_USUARIO) REFERENCES ALUNO (ID_USUARIO);
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

CREATE TABLE DESCONTO (
	ID_DESCONTO BIGINT PRIMARY KEY NOT NULL,
	NOME_DESCONTO VARCHAR(30) NOT NULL,
	PERCENTUAL_DESCONTO NUMERIC(5,2) NOT NULL;
	DT_INICIO TIMESTAMP NOT NULL,
	DT_FIM TIMESTAMP NOT NULL
);

CREATE SEQUENCE DESCONTO_ID_SEQ;
ALTER TABLE DESCONTO ALTER COLUMN ID_DESCONTO SET DEFAULT NEXTVAL('DESCONTO_ID_SEQ');

CREATE TABLE TIPO_AVALIACAO (
	ID_TIPO_AVALIACAO BIGINT PRIMARY KEY NOT NULL,
	NOME_TIPO_AVALIACAO VARCHAR(30) NOT NULL
);

INSERT INTO TIPO_AVALIACAO (ID_TIPO_AVALIACAO, NOME_TIPO_AVALIACAO) VALUES (1,'Prova');
COMMIT;
INSERT INTO TIPO_AVALIACAO (ID_TIPO_AVALIACAO, NOME_TIPO_AVALIACAO) VALUES (2,'Trabalho');
COMMIT;

CREATE TABLE AVALIACAO (
	ID_AVALIACAO BIGINT PRIMARY KEY NOT NULL,
	NOME_AVALIACAO VARCHAR(30) NOT NULL,
	OBS_AVALIACAO VARCHAR(100),
	ID_TIPO_AVALIACAO BIGINT NOT NULL
);

CREATE SEQUENCE AVALIACAO_ID_SEQ;
ALTER TABLE AVALIACAO ALTER COLUMN ID_AVALIACAO SET DEFAULT NEXTVAL('AVALIACAO_ID_SEQ');
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_TIPO FOREIGN KEY (ID_TIPO_AVALIACAO) REFERENCES TIPO_AVALIACAO (ID_TIPO_AVALIACAO);

CREATE TABLE DESCONTO_APLICADO (
	ID_DESCONTO_APLICADO BIGINT PRIMARY KEY NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	ID_MODULO BIGINT NOT NULL,
	ID_DESCONTO BIGINT NOT NULL,
	OBS_DESCONTO_APLICADO VARCHAR(100) NOT NULL
);

CREATE SEQUENCE DESCONTO_APLICADO_ID_SEQ;
ALTER TABLE DESCONTO_APLICADO ALTER COLUMN ID_DESCONTO_APLICADO SET DEFAULT NEXTVAL('DESCONTO_APLICADO_ID_SEQ');
ALTER TABLE DESCONTO_APLICADO ADD CONSTRAINT FK_DESCONTO_APLICADO_ALUNO FOREIGN KEY (ID_USUARIO) REFERENCES ALUNO (ID_USUARIO);
ALTER TABLE DESCONTO_APLICADO ADD CONSTRAINT FK_DESCONTO_APLICADO_MODULO FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO);
ALTER TABLE DESCONTO_APLICADO ADD CONSTRAINT FK_DESCONTO_APLICADO_DESCONTO FOREIGN KEY (ID_DESCONTO) REFERENCES DESCONTO (ID_DESCONTO);

